<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="xunit.assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApiHub.Shared\ApiHub.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>